// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactSplitForm from "@/components/sections/contact/ContactSplitForm";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactSplitForm
        textAnimation="slide-up"
        tag="Contact Us"
        title="Request a Free Estimate"
        description="Located at 228 Sora Ter SE, Calgary, AB. Call us at (587) 572-2549. Open Mon–Sat 7am–6pm (Closed Sundays)."
        inputs={[
                  { name: "name", type: "text", placeholder: "Full Name", required: true },
                  { name: "email", type: "email", placeholder: "Email Address", required: true },
                  { name: "phone", type: "tel", placeholder: "Phone Number" },
                ]}
        textarea={{ name: "message", placeholder: "Describe your plumbing issue...", rows: 4, required: true }}
        buttonText="Send Request"
        imageSrc="https://storage.googleapis.com/webild/default/templates/plumber/contact.webp"
      />
            </div>
  );
}
