// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from "@/components/sections/faq/FaqSimple";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
              <FaqSimple
                textAnimation="slide-up"
                tag="FAQ"
                title="Frequently Asked Questions"
                description="Everything you need to know before booking a plumber."
                items={[
                  {
                    question: "Do you offer 24/7 emergency service?",
                    answer: "Yes. We have licensed plumbers on call around the clock, including weekends and holidays. If you have a burst pipe, gas leak, or major overflow, call us and we'll dispatch someone immediately.",
                  },
                  {
                    question: "Are your plumbers licensed and insured?",
                    answer: "Every plumber on our team is fully licensed, bonded, and insured. We carry general liability and workers' compensation coverage so you're protected from start to finish.",
                  },
                  {
                    question: "How much does a typical service call cost?",
                    answer: "We provide free estimates for most jobs. Our service call fee covers the initial inspection, and we always quote the full price before any work begins — no surprises on the bill.",
                  },
                  {
                    question: "Do you offer warranties on your work?",
                    answer: "All of our repairs and installations come with a 1-year labor warranty. Many of the parts and fixtures we install also carry manufacturer warranties of up to 10 years.",
                  },
                  {
                    question: "Can you help with bathroom or kitchen remodels?",
                    answer: "Absolutely. We handle all plumbing aspects of remodels — from rerouting supply and drain lines to installing new fixtures, showers, tubs, and dishwashers.",
                  },
                ]}
              />
            </div>
  );
}
