// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroCenteredLogos from "@/components/sections/hero/HeroCenteredLogos";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroCenteredLogos
        textAnimation="slide-up"
        avatarsSrc={[
                  "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-1.webp",
                  "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-2.webp",
                  "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-3.webp",
                ]}
        avatarText="Trusted by 1,200+ homeowners"
        title="Expert Plumbing You Can Trust"
        description="Professional plumbing and heating services in Calgary. Open Mon–Sat 7:00 AM – 6:00 PM (Closed Sundays)."
        primaryButton={{ text: "Schedule Service", href: "#contact" }}
        secondaryButton={{"text":"(587) 572-2549","href":"tel:5875722549"}}
        names={["Licensed & Insured", "24/7 Emergency Service", "15+ Years Experience", "100% Satisfaction Guarantee", "Free Estimates", "1,200+ Jobs Completed"]}
        imageSrc="https://storage.googleapis.com/webild/default/templates/plumber/hero.webp"
      />
            </div>
  );
}
