// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "reviews" section.

import React from 'react';
import TestimonialRatingCards from "@/components/sections/testimonial/TestimonialRatingCards";

export default function ReviewsSection(): React.JSX.Element {
  return (
    <div id="reviews" data-section="reviews">
              <TestimonialRatingCards
                textAnimation="slide-up"
                tag="Testimonials"
                title="What Our Customers Say"
                description="Real reviews from homeowners who trust FlowRight with their plumbing."
                testimonials={[
                  {
                    name: "Sarah K.",
                    role: "Homeowner, Denver CO",
                    quote: "They found a hidden leak behind our kitchen wall in minutes. Fixed it the same day and patched the drywall too. Absolutely top-notch service from start to finish.",
                    rating: 5,
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-1.webp",
                  },
                  {
                    name: "Mike T.",
                    role: "Homeowner, Boulder CO",
                    quote: "Our water heater died on a Sunday morning. FlowRight had a new tankless unit installed by the afternoon. Fair pricing and zero pressure to upsell. Will use them again.",
                    rating: 5,
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-2.webp",
                  },
                  {
                    name: "Jessica L.",
                    role: "Property Manager, Aurora CO",
                    quote: "We manage 40+ rental units and FlowRight handles all our plumbing. Always responsive, always professional. They've saved us a fortune in emergency repairs.",
                    rating: 5,
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-3.webp",
                  },
                ]}
              />
            </div>
  );
}
