// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesMediaCards from "@/components/sections/features/FeaturesMediaCards";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesMediaCards
                textAnimation="slide-up"
                tag="Our Services"
                title="What We Fix"
                description="Residential and commercial plumbing services — done right the first time."
                items={[
                  {
                    title: "Leak Detection & Repair",
                    description: "Advanced leak detection technology to find and fix hidden leaks before they cause major damage to your property.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service1.webp",
                  },
                  {
                    title: "Drain Cleaning",
                    description: "Professional drain clearing using hydro jetting and snaking to restore full flow and prevent future clogs.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service2.webp",
                  },
                  {
                    title: "Water Heater Installation",
                    description: "Tank and tankless water heater installs with energy-efficient options to lower your utility bills.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service3.webp",
                  },
                  {
                    title: "Bathroom Remodeling",
                    description: "Complete bathroom plumbing for renovations — fixture upgrades, pipe rerouting, and code-compliant installs.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service4.webp",
                  },
                  {
                    title: "Sewer Line Repair",
                    description: "Trenchless sewer repair and replacement that fixes the problem without tearing up your yard.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service5.webp",
                  },
                  {
                    title: "Emergency Plumbing",
                    description: "24/7 emergency response for burst pipes, overflows, and gas leaks — we're there when you need us most.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/plumber/service6.webp",
                  },
                ]}
              />
            </div>
  );
}
