// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-us" section.

import React from 'react';
import { Wrench, Droplets, ShieldCheck } from "lucide-react";
import FeaturesBorderGlow from "@/components/sections/features/FeaturesBorderGlow";

export default function WhyUsSection(): React.JSX.Element {
  return (
    <div id="why-us" data-section="why-us">
              <FeaturesBorderGlow
                textAnimation="slide-up"
                tag="Our Promise"
                title="Why Choose FlowRight"
                description="Numbers and values that speak for themselves."
                features={[
                  { icon: Wrench, title: "15+ Years of Experience", description: "Over a decade and a half of solving plumbing problems for homes and businesses across Denver." },
                  { icon: Droplets, title: "1,200+ Jobs Completed", description: "From quick fixes to full remodels, we've successfully completed thousands of plumbing projects." },
                  { icon: ShieldCheck, title: "Licensed & Certified", description: "Every plumber on our team is fully licensed, bonded, and insured for your peace of mind." },
                ]}
              />
            </div>
  );
}
